import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import ThemeProvider from "@/components/providers/ThemeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "@/components/AppSidebar";

import { Inter, Norican } from "next/font/google";

const norican = Norican({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-norican",
});

const inter = Inter({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-screen overflow-x-hidden">
      <head>
        <ThemeProvider/>
      </head>
      <body
            className={`${norican.variable} ${inter.variable} antialiased w-screen css-selector dark:dark-css-selector`}
            >
        <SidebarProvider>
          <main className="w-full">
            <AppSidebar/>
            <Navbar/>
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
